language: node_js
node_js:
  - "0.10"
  - "0.8"

before_script:
  - rm -R node_modules/jake
  - rm -R node_modules/utilities
  - rm -R -f node_modules/geddy
  - rm -R -f node_modules/geddy-genutils
  - rm -R -f node_modules/geddy-gen-model
  - rm -R -f node_modules/geddy-gen-controller
  - rm -R -f node_modules/geddy-gen-resource
  - rm -R -f node_modules/geddy-gen-view
  - rm -R -f node_modules/geddy-gen-app
  - npm install https://github.com/mde/jake/archive/master.tar.gz
  - npm install https://github.com/mde/utilities/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy-genutils/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy-gen-model/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy-gen-controller/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy-gen-resource/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy-gen-view/archive/master.tar.gz
  - npm install https://github.com/geddy/geddy-gen-app/archive/master.tar.gz

script: node_modules/jake/bin/cli.js test --trace
